### ISSUE TITLE
Would this work as I set it up? I tried but not working?

### ISSUE THREAD

**Issue by SupaYoshi** [RabidCrab/Minecraft.Vote#1]
I setup a custom vote, but it wont work yet ;)
Can you please help me ? Thanks!

I have essentials the command to jail is:
/jail playername jail1 1d

Now i want to make a vote: Would this work well?

Few questions?
- The jail1, can it be put in automaticly by he plugin.
- 1d has to be put in by the player or any other time

Would this work?

http://pastebin.com/XJrafZdX

**Comment by RabidCrab** [comment]
Sorry, didn't notice this until a whopping 3 years later =/. I primarily used the dev.bukkit website to communicate.
