### ISSUE TITLE
Vote, bad async call

### ISSUE THREAD

**Issue by Xarias09** [RabidCrab/Minecraft.Vote#2]
Vote: 1.4.6_01
Spigot: 763

Pastebin: http://pastebin.com/3w8Utwty

**Comment by Xarias09** [comment]
Here is pastebin from 1.5.1 version;
http://pastebin.com/yenStpWu

**Comment by TNTUP** [comment]
Sorry to comment on an way old older bug report, but I can't say if its the same bug as you but those pastes are deleted, but I'm bumping this bug report to 2016 and here is it https://hasteb.in/vuyejipupu.vbs (Running on PaperSpigot)

**Comment by RabidCrab** [comment]
Looks like Java doesn't like it when you recycle timers. I'll take a look at it tomorrow evening when I have the free time to test it out.

**Comment by RabidCrab** [comment]
Looks like since the beginning I wasn't using the Bukkit scheduler like I thought I was.

I shifted the timer into a thread safe scheduler call, which should fix the problem. 1.9_03 has been submitted and should be available in a few hours.

**Comment by TNTUP** [comment]
Thanks for this fast fix!
